# file: .github/workflows/hello-world.yml
name: hello-world
# on ‚Äì –æ–ø—Ä–µ–¥–µ–ª—è–µ—Ç —Å–æ–±—ã—Ç–∏—è, –∫–æ—Ç–æ—Ä—ã–µ –∑–∞–ø—É—Å–∫–∞—é—Ç –≤–æ—Ä–∫—Ñ–ª–æ—É
on: push
jobs:
  # build ‚Äì –ø—Ä–æ–∏–∑–≤–æ–ª—å–Ω–æ –≤—ã–±—Ä–∞–Ω–Ω–æ–µ –∏–º—è –∑–∞–¥–∞–Ω–∏—è
  # –∏—Ö –º–æ–∂–µ—Ç –±—ã—Ç—å –±–æ–ª—å—à–µ –æ–¥–Ω–æ–≥–æ
  build:
    # –æ–ø–µ—Ä–∞—Ü–∏–æ–Ω–Ω–∞—è —Å–∏—Å—Ç–µ–º–∞ –¥–ª—è —Ä–∞–±–æ—Ç—ã –≤–æ—Ä–∫—Ñ–ª–æ—É
    runs-on: ubuntu-latest
    steps: # —Å–ø–∏—Å–æ–∫ —à–∞–≥–æ–≤, –∫–æ—Ç–æ—Ä—ã–µ –Ω–∞–¥–æ –≤—ã–ø–æ–ª–Ω–∏—Ç—å
      - run: echo "üéâ The job was automatically triggered"
